name: Generate Songbook Artifacts
run-name: ${{ github.actor }} is generating artifacts
on:
  workflow_dispatch:
    inputs:
      epub:
        description: 'Generate epub'
        required: false
        type: boolean
        default: true
      pdf:
        description: 'Generate pdf'
        required: false
        type: boolean
        default: true
      html:
        description: 'Generate htmls'
        required: false
        type: boolean
        default: true
  push:
    branches:
      - 'main'
jobs:
  Generate-artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Generating a songbook PDF triggered by ${{ github.event_name }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: sudo snap install libxslt
      - run: sudo apt-get install libxml2
      - run: sudo apt-get install python3-lxml
      - run: pip3 install -r ${{ github.workspace }}/requirements.txt
      - run: pip install lxml

      - if: ${{ inputs.pdf }}
        run: sudo apt-get install texlive texlive-latex-extra texlive-lang-polish
      - if: ${{ inputs.pdf }}
        run: cd  ${{ github.workspace }} && chmod 755 ./render_pdf.sh && ./render_pdf.sh songbook a5 "Śpiewnik $(date +'%Y-%m-%d')" songs/*.xml
      - if: ${{ inputs.pdf }}
        run: mv ${{ github.workspace }}/build/output.pdf ${{ github.workspace }}/build/songbook_a5.pdf
      - if: ${{ inputs.pdf }}
        run: cd  ${{ github.workspace }} && ./render_pdf.sh songbook a4 "Śpiewnik $(date +'%Y-%m-%d')" songs/*.xml
      - if: ${{ inputs.pdf }}
        run: mv ${{ github.workspace }}/build/output.pdf ${{ github.workspace }}/build/songbook_a4.pdf
      - name: Upload A4 PDF
        if: ${{ inputs.pdf }}
        uses: actions/upload-artifact@v3
        with:
         name: songbook_a4
         path: ${{ github.workspace }}/build/songbook_a4.pdf
      - name: Upload A5 PDF
        if: ${{ inputs.pdf }}
        uses: actions/upload-artifact@v3
        with:
          name: songbook_a5
          path: ${{ github.workspace }}/build/songbook_a5.pdf

      - run: echo "DONE"