name: Generate Songbook Artifacts
run-name: ${{ github.actor }} is generating artifacts
on:
  workflow_dispatch:
    inputs:
      epub:
        description: 'Generate epub'
        required: false
        type: boolean
        default: true
      pdf:
        description: 'Generate pdf'
        required: false
        type: boolean
        default: true
      html:
        description: 'Generate htmls'
        required: false
        type: boolean
        default: true
  push:
    branches:
      - 'main'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  Generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Generating a songbook PDF triggered by ${{ github.event_name }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: sudo snap install libxslt
      - run: sudo apt-get install libxml2
      - run: sudo apt-get install python3-lxml
      - run: sudo apt-get install texlive
      - run: pip install -r ${{ github.workspace }}/requirements.txt
      - run: cd  ${{ github.workspace }} && chmod 755 ./render_pdf.sh && ./render_pdf.sh songbook a5 "Śpiewnik $(date +'%Y-%m-%d')" songs/*.xml
      - run: mv ${{ github.workspace }}/build/output.pdf ${{ github.workspace }}/build/songbook_a5.pdf'
      - run: cd  ${{ github.workspace }} && ./render_pdf.sh songbook a4 "Śpiewnik $(date +'%Y-%m-%d')" songs/*.xml
      - run: mv ${{ github.workspace }}/build/output.pdf ${{ github.workspace }}/build/songbook_a4.pdf
      - name: Upload A4 PDF
        uses: actions/upload-artifact@v3
        with:
         name: songbook_a4
         path: ${{ github.workspace }}/build/songbook_a4.pdf
      - name: Upload A5 PDF
        uses: actions/upload-artifact@v3
        with:
          name: songbook_a5
          path: ${{ github.workspace }}/build/songbook_a5.pdf
      - run: echo "DONE"